gmr_dof_names:
  - waist_y_joint
  - waist_x_joint
  - waist_z_joint

  - l_hip_y_joint
  - l_hip_x_joint
  - l_hip_z_joint
  - l_knee_y_joint
  - l_ankle_y_joint
  - l_ankle_x_joint

  - r_hip_y_joint 
  - r_hip_x_joint
  - r_hip_z_joint
  - r_knee_y_joint
  - r_ankle_y_joint
  - r_ankle_x_joint

  - l_shoulder_y_joint
  - l_shoulder_x_joint
  - l_shoulder_z_joint
  - l_elbow_y_joint
  - l_wrist_x_joint
  - l_wrist_y_joint
  - l_wrist_z_joint

  - r_shoulder_y_joint
  - r_shoulder_x_joint
  - r_shoulder_z_joint
  - r_elbow_y_joint
  - r_wrist_x_joint
  - r_wrist_y_joint
  - r_wrist_z_joint

lab_dof_names:
  - waist_y_joint
  - waist_x_joint
  - waist_z_joint

  - l_hip_y_joint
  - l_hip_x_joint
  - l_hip_z_joint
  - l_knee_y_joint
  - l_ankle_y_joint
  - l_ankle_x_joint

  - r_hip_y_joint 
  - r_hip_x_joint
  - r_hip_z_joint
  - r_knee_y_joint
  - r_ankle_y_joint
  - r_ankle_x_joint

  - l_shoulder_y_joint
  - l_shoulder_x_joint
  - l_shoulder_z_joint
  - l_elbow_y_joint
  - l_wrist_x_joint
  - l_wrist_y_joint
  - l_wrist_z_joint

  - r_shoulder_y_joint
  - r_shoulder_x_joint
  - r_shoulder_z_joint
  - r_elbow_y_joint
  - r_wrist_x_joint
  - r_wrist_y_joint
  - r_wrist_z_joint


# Names of the key bodies that will be used in further processing
# Must match the names in the lab robot model
# Order matters and should align with that used in observation
lab_key_body_names:
  - l_ankle_x_link 
  - r_ankle_x_link
  - l_wrist_z_link
  - r_wrist_z_link
  - l_shoulder_x_link
  - r_shoulder_x_link
