gmr_dof_names:
  - loin_yaw_joint_motor

  - leg_l1_joint_motor
  - leg_l2_joint_motor
  - leg_l3_joint_motor
  - leg_l4_joint_motor
  - leg_l5_joint_motor

  - leg_r1_joint_motor
  - leg_r2_joint_motor
  - leg_r3_joint_motor
  - leg_r4_joint_motor
  - leg_r5_joint_motor

  - l_shoulder_pitch_joint_motor
  - l_shoulder_roll_joint_motor
  - l_shoulder_yaw_joint_motor
  - l_arm_pitch_joint_motor

  - r_shoulder_pitch_joint_motor
  - r_shoulder_roll_joint_motor
  - r_shoulder_yaw_joint_motor
  - r_arm_pitch_joint_motor


lab_dof_names:
  - left_hip_pitch_joint
  - right_hip_pitch_joint
  - waist_yaw_joint
  - left_hip_roll_joint
  - right_hip_roll_joint
  - waist_roll_joint
  - left_hip_yaw_joint
  - right_hip_yaw_joint
  - waist_pitch_joint
  - left_knee_joint
  - right_knee_joint
  - left_shoulder_pitch_joint
  - right_shoulder_pitch_joint
  - left_ankle_pitch_joint
  - right_ankle_pitch_joint
  - left_shoulder_roll_joint
  - right_shoulder_roll_joint
  - left_ankle_roll_joint
  - right_ankle_roll_joint
  - left_shoulder_yaw_joint
  - right_shoulder_yaw_joint
  - left_elbow_joint
  - right_elbow_joint
  - left_wrist_roll_joint
  - right_wrist_roll_joint
  - left_wrist_pitch_joint
  - right_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_wrist_yaw_joint


# Names of the key bodies that will be used in further processing
# Must match the names in the lab robot model
# Order matters and should align with that used in observation
lab_key_body_names:
  - left_ankle_roll_link
  - right_ankle_roll_link
  - left_wrist_yaw_link
  - right_wrist_yaw_link
  - left_shoulder_roll_link
  - right_shoulder_roll_link
